#!/usr/bin/python

# This file is part of the kbremap project.
# Copyright (C) 2014 Nicolas Malarmey
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
# contact: elmamyra@gmail.com

import argparse
from kbremap_app import server



parser = argparse.ArgumentParser()

parser.add_argument("-s", "--start", action="store_true",
                    help="start the server")
parser.add_argument("-p", "--pause", action="store_true",
                    help="pause/resume the server")
parser.add_argument("-q", "--quit", action="store_true",
                    help="close the server")
parser.add_argument("-d", "--debug", action="store_true", 
                    help="show log in console")
parser.add_argument("-e", "--editor", action="store_true", 
                    help="Start the editor")


args = parser.parse_args()

if args.start:
    server.start(args.debug)
elif args.quit:
    server.close()
elif args.pause:
    server.pause()
elif args.editor:
    from kbremap_app.client import mainWindow
    mainWindow.start()
else:
    parser.print_help()
