#!/usr/bin/python
# -*- coding: utf-8 -*-
from PySide.QtGui import QApplication
from PySide.QtCore import QCoreApplication, QLocale, QLibraryInfo, QTranslator

from speedy_keyboard_editor import mainWindow, info
import sys

app = QApplication(sys.argv)
locale = QLocale.system().name()
translator=QTranslator ()
translator.load("qt_" + locale,   
                QLibraryInfo.location(QLibraryInfo.TranslationsPath))
app.installTranslator(translator)
QApplication.setApplicationName(info.name)
QApplication.setApplicationVersion(info.version)
QApplication.setOrganizationName(info.name)
QApplication.setOrganizationDomain(info.domain)
win = mainWindow.MainWindow()
sys.exit(app.exec_())


